### ISSUE TITLE
empty string as 4th council member for marmaj.sputnikdao.near 

### ISSUE THREAD

**Issue by chloethedev** [near-daos/sputnik-dao-ui-legacy#10]
Created a SputnikDAO using sputnik.fund. Hit enter after the 3rd council member. DAO got created with 3 NEAR accounts and 1 empty string. 

Link to DAO with issue: https://sputnik.fund/#/marmaj.sputnikdao.near

**Comment by AngelBlock** [comment]
Will be fixed in v2
