### ISSUE TITLE
Stats page for DAOs

### ISSUE THREAD

**Issue by ilblackdragon** [near-daos/sputnik-dao-ui-legacy#5]
Would be great to see next stats:
 - [ ] Graph over time of DAOs: total and weekly active
 - [ ] Total amount of tokens locked in Sputnik DAOs + graph of amounts over time
 - [ ] Total distributed funds + graph of distribution over time
 - [ ] what else?

The information can be retrieved by querying indexer nodes.

**Comment by DenysOf** [comment]
Please elaborate on `Graph over time of DAOs: total and weekly active` active users/ DAOs, etc?

**Comment by AngelBlock** [comment]
The stats site is being developed at https://github.com/Stardust-Staking/stats-sputnik-dao, please add desired functions there.
