### ISSUE TITLE
new DAO form hint does not match rule

### ISSUE THREAD

**Issue by amgando** [near-daos/sputnik-dao-ui-legacy#7]
- hint text says "Please enter between 2 and 30 chars, no spaces, lowercase" 
- but validation checks for min 4, max 29 chars in a DAO name
- NEAR requires [min 2, max 64](https://nomicon.io/DataStructures/Account.html#account-id-rules) chars

https://github.com/near-daos/sputnik-dao-ui/blob/f625c70761e7f5f9db539ef24cb152fa2fc19f83/src/Selector.jsx#L195-L202

**Comment by DenysOf** [comment]
Fixed hint / validation inconsistencies. Now UI allows for min 2 / max 35.
Form validates prefix (sub account), full account is 64 chars, less 24 chars length of testnet master account, rounded down to 35. If someone require > 35 chars account, please reopen - we will consider using 12 char mainnet account as a base for calculation, but in this case validation will fail on the testnet.
