### ISSUE TITLE
Show countdown to the end of the vote for each proposal

### ISSUE THREAD

**Issue by murilooon** [near-daos/sputnik-dao-ui-legacy#8]
## Expected Behavior

- [ ] You should be able to see, in a proposal, a countdown to the end of the vote phase.

**Comment by DenysOf** [comment]
Perhaps it makes sense to show the countdown when due time is near, not during the whole proposal timeframe, what do you think?

**Comment by murilooon** [comment]
This is the information we currently have:
![image](https://user-images.githubusercontent.com/16845851/109034388-5b19d380-76a6-11eb-80e4-93d63364fdc9.png)

Thinking now, it actually needs a proposal start date too. When you open a proposal you can see vote period in days, but you don't know when it started and when it will finish. Maybe these two information are more important than a countdown...

**Comment by AngelBlock** [comment]
Will be done in v2
